name: TownyChat
main: com.palmergames.bukkit.TownyChat.Chat
version: 0.12
author: ElgarL, Shade
website: http://code.google.com/a/eclipselabs.org/p/towny/
description: >
    TownyChat plugin which hooks Towny.

softdepend: [Towny]

commands:
