package com.palmergames.bukkit.config;


public enum ConfigNodes {
	    VERSION("version.version",""),
	    LAST_RUN_VERSION("version.last_run_version",""),
	    LANGUAGE("language","english.yml"),
	    PERMS("permissions",""),
	    PERMS_TOWN_CREATION_ADMIN_ONLY("permissions.town_creation_admin_only",""),
	    PERMS_NATION_CREATION_ADMIN_ONLY("permissions.nation_creation_admin_only",""),
	    LEVELS("levels",""),
	    LEVELS_TOWN_LEVEL("levels.town_level",""),
	    LEVELS_NATION_LEVEL("levels.nation_level",""),  
	    TOWN("town",""),
	    TOWN_MAX_PLOTS_PER_RESIDENT("town.max_plots_per_resident",""),
	    TOWN_LIMIT("town.town_limit",""),
	    TOWN_MIN_DISTANCE_FROM_TOWN_HOMEBLOCK("town.min_distance_from_town_homeblock",""),
	    TOWN_MAX_DISTANCE_BETWEEN_HOMEBLOCKS("town.max_distance_between_homeblocks",""),
	    TOWN_TOWN_BLOCK_RATIO("town.town_block_ratio",""),
	    TOWN_TOWN_BLOCK_SIZE("town.town_block_size",""),
	    FLAGS_RES_FR_BUILD("default_perm_flags.resident.friend.build",""),
	    FLAGS_RES_FR_DESTROY("default_perm_flags.resident.friend.destroy",""),
	    FLAGS_RES_FR_ITEM_USE("default_perm_flags.resident.friend.item_use",""),
	    FLAGS_RES_FR_SWITCH("default_perm_flags.resident.friend.switch",""),
	    FLAGS_RES_ALLY_BUILD("default_perm_flags.resident.ally.build",""),
	    FLAGS_RES_ALLY_DESTROY("default_perm_flags.resident.ally.destroy",""),
	    FLAGS_RES_ALLY_ITEM_USE("default_perm_flags.resident.ally.item_use",""),
	    FLAGS_RES_ALLY_SWITCH("default_perm_flags.resident.ally.switch",""),
	    FLAGS_RES_OUTSIDER_BUILD("default_perm_flags.resident.outsider.build",""),
	    FLAGS_RES_OUTSIDER_DESTROY("default_perm_flags.resident.outsider.destroy",""),
	    FLAGS_RES_OUTSIDER_ITEM_USE("default_perm_flags.resident.outsider.item_use",""),
	    FLAGS_RES_OUTSIDER_SWITCH("default_perm_flags.resident.outsider.switch",""),
	    FLAGS_TOWN_RES_BUILD("default_perm_flags.town.resident.build",""),
	    FLAGS_TOWN_RES_DESTROY("default_perm_flags.town.resident.destroy",""),
	    FLAGS_TOWN_RES_ITEM_USE("default_perm_flags.town.resident.item_use",""),
	    FLAGS_TOWN_RES_SWITCH("default_perm_flags.town.resident.switch",""),
	    FLAGS_TOWN_ALLY_BUILD("default_perm_flags.town.ally.build",""),
	    FLAGS_TOWN_ALLY_DESTROY("default_perm_flags.town.ally.destroy",""),
	    FLAGS_TOWN_ALLY_ITEM_USE("default_perm_flags.town.ally.item_use",""),
	    FLAGS_TOWN_ALLY_SWITCH("default_perm_flags.town.ally.switch",""),
	    FLAGS_TOWN_OUTSIDER_BUILD("default_perm_flags.town.outsider.build",""),
	    FLAGS_TOWN_OUTSIDER_DESTROY("default_perm_flags.town.outsider.destroy",""),
	    FLAGS_TOWN_OUTSIDER_ITEM_USE("default_perm_flags.town.outsider.item_use",""),
	    FLAGS_TOWN_OUTSIDER_SWITCH("default_perm_flags.town.outsider.switch",""),
	    NWS("new_world_settings",""),
	    NWS_FORCE_PVP_ON("new_world_settings.force_pvp_on",""),
	    NWS_DISABLE_PLAYER_CROP_TRAMPLING("new_world_settings.disable_player_crop_trampling",""),
	    NWS_DISABLE_CREATURE_CROP_TRAMPLING("new_world_settings.disable_creature_crop_trampling",""),
	    NWS_WORLD_MONSTERS_ON("new_world_settings.world_monsters_on",""),
	    NWS_FORCE_EXPLOSIONS_ON("new_world_settings.force_explosions_on",""),
	    NWS_FORCE_TOWN_MONSTERS_ON("new_world_settings.force_town_monsters_on",""),
	    NWS_FORCE_FIRE_ON("new_world_settings.force_fire_on",""),
	    GTOWN_SETTINGS_FRIENDLY_FIRE("global_town_settings.friendly_fire",""),
	    GTOWN_SETTINGS_HEALTH_REGEN("global_town_settings.health_regen",""),
	    GTOWN_SETTINGS_REGEN_SPEED("global_town_settings.health_regen.speed",""),
	    GTOWN_SETTINGS_REGEN_ENABLE("global_town_settings.health_regen.enable",""),
	    GTOWN_SETTINGS_DAILY_TAXES("global_town_settings.daily_taxes",""),
	    GTOWN_SETTINGS_ALLOW_OUTPOSTS("global_town_settings.allow_outposts",""),
	    GTOWN_SETTINGS_ALLOW_TOWN_SPAWN("global_town_settings.allow_town_spawn",""),
	    GTOWN_SETTINGS_ALLOW_TOWN_SPAWN_TRAVEL("global_town_settings.allow_town_spawn_travel",""),
	    GTOWN_SETTINGS_TOWN_RESPAWN("global_town_settings.town_respawn",""),
	    GTOWN_SETTINGS_PREVENT_TOWN_SPAWN_IN("global_town_settings.prevent_town_spawn_in",""),
	    GTOWN_SETTINGS_SHOW_TOWN_NOTIFICATIONS("global_town_settings.show_town_notifications",""),
	    PLUGIN_DATABASE_LOAD("plugin.database.database_load",""),
	    PLUGIN_DATABASE_SAVE("plugin.database.database_save",""),
	    PLUGIN_DAILY_BACKUPS("plugin.database.daily_backups",""),
	    PLUGIN_FLATFILE_BACKUP("plugin.database.flatfile_backup",""),
	    PLUGIN_USING_ESSENTIALS("plugin.interfacing.using_essentials",""),
	    PLUGIN_USING_ICONOMY("plugin.interfacing.using_iconomy",""),
	    PLUGIN_USING_QUESTIONER("plugin.interfacing.using_questioner",""),
	    PLUGIN_USING_PERMISSIONS("plugin.interfacing.using_permissions",""),
	    PLUGIN_DAY_INTERVAL("plugin.day_interval",""),
	    PLUGIN_DEBUG_MODE("plugin.debug_mode",""),
	    PLUGIN_DEV_MODE("plugin.dev_mode",""),
	    PLUGIN_DEV_MODE_ENABLE("plugin.dev_mode.enable",""),
	    PLUGIN_DEV_MODE_DEV_NAME("plugin.dev_mode.dev_name",""),
	    PLUGIN_LOGGING("plugin.LOGGING",""),
	    PLUGIN_RESET_LOG_ON_BOOT("plugin.reset_log_on_boot",""),
	    FILTERS_NPC_PREFIX("filters_colour_chat.npc_prefix",""),
	    FILTERS_REGEX("filters_colour_chat.regex",""),
	    FILTERS_REGEX_NAME_FILTER_REGEX("filters_colour_chat.regex.name_filter_regex",""),
	    FILTERS_REGEX_NAME_CHECK_REGEX("filters_colour_chat.regex.name_check_regex",""),
	    FILTERS_REGEX_NAME_REMOVE_REGEX("filters_colour_chat.regex.name_remove_regex",""),
	    FILTERS_MODIFY_CHAT("filters_colour_chat.modify_chat",""),
	    FILTERS_MODIFY_CHAT_ENABLE("filters_colour_chat.modify_chat.enable",""),
	    FILTERS_MODIFY_CHAT_FORMAT("filters_colour_chat.modify_chat.format",""),
	    FILTERS_COLOUR("filters_colour_chat.colour",""),
	    FILTERS_COLOUR_KING("filters_colour_chat.colour.king",""),
	    FILTERS_COLOUR_MAYOR("filters_colour_chat.colour.mayor",""),
	    PROT_ITEM_USE_ID("protection.item_use_ids",""),
	    PROT_SWITCH_ID("protection.switch_ids",""),
	    PROT_MOB_REMOVE_TOWN("protection.town_mob_removal_entities",""),
	    PROT_MOB_REMOVE_WORLD("protection.world_mob_removal_entities",""),
	    PROT_MOB_REMOVE_SPEED("protection.mob_removal_speed",""),
	    PROT_CHEAT("protection.cheat_protection",""),
	    UNCLAIMED_ZONE_BUILD("unclaimed.unclaimed_zone_build",""),
	    UNCLAIMED_ZONE_DESTROY("unclaimed.unclaimed_zone_destroy",""),
	    UNCLAIMED_ZONE_ITEM_USE("unclaimed.unclaimed_zone_item_use",""),
	    UNCLAIMED_ZONE_IGNORE("unclaimed.unclaimed_zone_ignore",""),
	    UNCLAIMED_ZONE_SWITCH("unclaimed.unclaimed_zone_switch",""),
	    UNCLAIMED_ZONE_NAME("unclaimed.unclaimed_zone_name",""),
	    UNCLAIMED_PLOT_NAME("unclaimed.unclaimed_plot_name",""),
	    RES_SETTING("resident_settings",""),
	    RES_SETTING_INACTIVE_AFTER_TIME("resident_settings.inactive_after_time",""),
	    RES_SETTING_DELETE_OLD_RESIDENTS("resident_settings.delete_old_residents",""),
	    RES_SETTING_DELETE_OLD_RESIDENTS_ENABLE("resident_settings.delete_old_residents.enable",""),
	    RES_SETTING_DELETE_OLD_RESIDENTS_TIME("resident_settings.delete_old_residents.deleted_after_time",""),
	    RES_SETTING_DEFAULT_TOWN_NAME("resident_settings.default_town_name",""),
	    ECO("economy",""),
	    ECO_PRICE_TOWN_SPAWN_TRAVEL("economy.price_town_spawn_travel",""),
	    ECO_PRICE_TOWN_PUBLIC_SPAWN_TRAVEL("economy.price_town_public_spawn_travel",""),
	    ECO_PRICE_NATION_NEUTRALITY("economy.price_nation_neutrality",""),
	    ECO_PRICE_NEW_NATION("economy.price_new_nation",""),
	    ECO_PRICE_NEW_TOWN("economy.price_new_town",""),
	    ECO_PRICE_OUTPOST("economy.price_outpost",""),
	    ECO_PRICE_CLAIM_TOWNBLOCK("economy.price_claim_townblock",""),
	    ECO_PRICE_NATION_UPKEEP("economy.price_nation_upkeep",""),
	    ECO_PRICE_TOWN_UPKEEP("economy.price_town_upkeep",""),
	    ECO_PRICE_DEATH("economy.price_death",""),
	    ECO_PRICE_DEATH_WARTIME("economy.price_death_wartime",""),
	    WAR("war",""),
	    WARTIME_NATION_CAN_BE_NEUTRAL("war.wartime_nation_can_be_neutral",""),
	    WARTIME_REMOVE_ON_MONARCH_DEATH("war.wartime_remove_on_monarch_death",""),
	    WARTIME_WARNING_DELAY("war.wartime_warning_delay",""),
	    WARTIME_TOWN_BLOCK_HP("war.wartime_town_block_hp",""),
	    WARTIME_TOWN_BLOCK_LOSS_PRICE("war.wartime_town_block_loss_price",""),
	    WARTIME_HOME_BLOCK_HP("war.wartime_home_block_hp",""),
	    WARTIME_BASE_SPOILS("war.wartime_base_spoils",""),
	    WARTIME_POINTS_TOWNBLOCK("war.wartime_points_townblock",""),
	    WARTIME_POINTS_TOWN("war.wartime_points_town",""),
	    WARTIME_POINTS_NATION("war.wartime_points_nation",""),
	    WARTIME_POINTS_KILL("war.wartime_points_kill",""),
	    WARTIME_MIN_HEIGHT("war.wartime_min_height","");

		private final String Root;
		private final String Default; 
		
		private ConfigNodes(String root, String def) {  
			 this.Root = root;  
			 this.Default = def;
		}

		public String getRoot() {
			return Root;
		}
		
		public String getDefault() {
			return Default;
		}
			
	}